skills = [
    "Python",
    "HTML",
    "CSS",
    "Customer Service",
    "Dog Walking",
    "Medicine",
    "Digital Marketing",
    "Graphic Design",
    "Data Analysis",
    "Project Management",
    "Public Speaking",
    "Photography",
    "Content Writing",
    "Video Editing",
    "Mobile App Development",
    "UI/UX Design",
    "Salesforce",
    "Artificial Intelligence",
    "Social Media Marketing",
    "Cloud Computing",
    "Network Security",
    "Financial Planning",
    "Public Relations",
    "Event Planning",
    "Copywriting",
    "E-commerce",
    "Fitness Training",
    "Interior Design",
    "Web Development",
    "Search Engine Optimization (SEO)",
    "Customer Relationship Management (CRM)",
    "Data Science",
    "Machine Learning",
    "Agile Methodology",
    "Product Management",
    "Singing",
    "Content Marketing",
    "Culinary Arts",
    "Foreign Language Translation",
    "Game Development",
    "Human Resources",
    "Blogging",
    "User Research",
    "Fashion Design",
    "Illustration",
    "Video Game Design",
    "Email Marketing",
    "Business Analytics",
    "Financial Analysis",
    "Event Management",
    "Leadership Development",
    "Market Research",
    "Real Estate Investment",
    "Search Engine Marketing (SEM)",
    "Social Media Management",
    "Cloud Architecture",
    "Network Administration",
    "Tax Preparation",
    "Graphic Illustration",
    "Mobile Game Development",
    "User Interface Design",
    "Salesforce Administration",
    "Robotics",
    "Voice Acting",
    "Copy Editing",
    "Dropshipping",
    'Java',
    'JavaScript',
    'C++',
    'HTML',
    'CSS',
    'SQL',
    'React',
    'Angular',
    'Vue.js',
    'Node.js',
    'Django',
    'Flask',
    'Spring Framework',
    'Ruby on Rails',
    'C#',
    'ASP.NET',
    'PHP',
    'WordPress',
    'Swift',
    'Kotlin',
    'Android Development',
    'iOS Development'
    ]